### ISSUE TITLE
docfx: reduce the time that it takes to run test_hanging

### ISSUE THREAD

**Issue by dandhlee** [googleapis/doc-templates#104]
Currently it takes roughly 20 minutes for the hanging testcase when docfx runs with max parallelism, and more when it isn't run with as much parallelism on test machines / hardware differences / environment factors. In general, it would be nice if we can reduce the amount of time it takes to run the hanging testcase.

However we need to be careful not to only not reduce the time, but also ensure that with the old broken template that it still hangs on generation. The old template can be found on: https://github.com/googleapis/doc-templates/pull/68/files

**Comment by tbpg** [comment]
I think we can close this as the underlying issue that was causing the delay has been fixed.
