### ISSUE TITLE
docfx: remove fallback to default template

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#105]
Right now, doc-pipeline configures `docfx` to fall back to the `default` template:
https://github.com/googleapis/doc-pipeline/blob/6408a396aaf7aa1131a4dcba9a8a36af39258d4d/docpipeline/generate.py#L52-L55

This means that `docfx` first checks the `devsite` template for a file, then falls back to the `default` template if it doesn't exist. This allows you to quickly customize parts of a DocFX template.

As we customize more and more of the template, this can present a problem. The `default` template has more than we need for our project. For example, we know we'll never need a navbar. Also, there is a `toc.html` file in the `default` template, which we would prefer be named `toc.yaml`.

This can also cause confusion during development. Sometimes, you see surprising behavior caused by the `default` template, but you forget that the `default` template is lurking in the background. So, you can waste a lot of time debugging.

We can simplify our configuration by have a standalone template with everything we need.

The downside of this is that the `default` template sometimes gets improvements and bug fixes that we pick up automatically. If we have a standalone template, we don't get those automatic updates anymore. However, since we have already copied over and customized many of the `default` files, this is already a problem. So, making a standalone template wouldn't create a new problem, it just might make it a little worse.

I propose we drop the dependency on the `default` template.

To do that, we would:
* Copy everything we need from the `default` template to our `devsite` template.
* Update the tests in this repo to not fall back to `default`.
* Update doc-pipeline to not fall back to `default`.
* Rely on the golden tests to make sure there are no surprising changes.

We may or may not want to put a system in place so we don't forget to check for changes in the `default` template we might want to copy over to our template. But, the more we customize, the harder that will get.

cc @dandhlee @eaball35 @fhinkel @jskeet

**Comment by jskeet** [comment]
Sounds reasonable to me. We only need to pick up improvements and bugfixes that are actually relevant to us, of course... I suspect that some kind of bot that creates an issue *here* every time there's a change in the default template in docfx (with a link to the diff) would make it pretty straightforward to keep an eye on, for someone who understands the templates to start with.

**Comment by tbpg** [comment]
Done. :smiley:
