### ISSUE TITLE
docfx: rename toc.html to toc.yaml

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#108]
Right now, we generate a `toc.html` file, but it's actually YAML. With the switch to a standalone template (#105), we can rename the file to `toc.yaml`.

doc-pipeline will still need to rename the file from `toc.yaml` to `_toc.yaml`.

We'll need to keep support for `toc.html` until we're sure we have no more tarballs with `toc.html`. That may take a long time. So, we can mark this fixed as soon as the template is updated.

Steps:
1. Update doc-pipeline to support both filenames.
2. Update doc-templates to rename the `toc.html.*` files to `toc.yaml.*`.

**Comment by tbpg** [comment]
Docs about how files are named: https://dotnet.github.io/docfx/tutorial/intro_template.html#naming-rule-for-a-renderer-file

Make sure to get the `.js` file and the `.tmpl` file, otherwise you may see surprising results.

If there is a way to make the output file actually show up as `_toc.yaml` as part of this, that would be awesome. But, not essential.

**Comment by dandhlee** [comment]
I couldn't find a way to make use of docfx to try and add a prefix of the name from `toc.yaml` to `_toc.yaml`. Perhaps we can look into a method outside the docfx generator should we need.

**Comment by tbpg** [comment]
Sounds good. We have it working with doc-pipeline, so no need to put too much effort in here.

Thank you for the quick fix!
