### ISSUE TITLE
Code snippets don't include prettyprint class

### ISSUE THREAD

**Issue by jskeet** [googleapis/doc-templates#133]
## Expected Behavior

Snippets should have syntax highlighting.

## Actual Behavior

Syntax highlighting is not performed because the `code` HTML elements from snippets have `class="lang-cs"` or similar, but no `prettyprint` class

**Comment by tbpg** [comment]
I think this was fixed by https://github.com/googleapis/doc-pipeline/pull/62 -- closing.
