### ISSUE TITLE
docfx: fix source code highlighting

### ISSUE THREAD

**Issue by tbpg** [googleapis/doc-templates#33]
When there is a code block, it should be highlighted based on the language. We should figure out the right HTML classes to apply to the code block elements then update the template to use those instead of the existing classes.

https://github.com/googleapis/doc-templates/blob/c1349290a739e0cad1120e48537e59aef7fdf5a8/third_party/docfx/templates/devsite/partials/uref/namespace.tmpl.partial#L38-L40

**Comment by dandhlee** [comment]
Missed example code syntax highlighting
