### ISSUE TITLE
Add letter casing to type in summary intro sentence

### ISSUE THREAD

**Issue by dansaadati** [googleapis/doc-templates#416]
We should preserve letter casing for types in the [getSummaryIntroSentence function](https://github.com/googleapis/doc-templates/blob/main/third_party/docfx/templates/devsite/common.js#L118). For example, "Reference documentation and code samples for the Cloud Asset V1 API **class** AnalyzeIamPolicyLongrunningResponse." should be changed to "Reference documentation and code samples for the Cloud Asset V1 API **Class** AnalyzeIamPolicyLongrunningResponse.".

**Comment by tbpg** [comment]
Closing to archive this repo. Please reopen on https://github.com/googleapis/doc-pipeline if needed.
