### ISSUE TITLE
Template generation hangs for Node.js tarballs

### ISSUE THREAD

**Issue by fhinkel** [googleapis/doc-templates#83]
Template generation hangs for Node.js tarballs, e.g. docfx-nodejs-dialogflow-3.3.0.tar.gz, if any of[ these 5 lines ](https://github.com/googleapis/doc-templates/pull/68/files)are included. 

Can we remove/replace those lines?

**Comment by tbpg** [comment]
Assigning to @dandhlee for a test case for this scenario. https://github.com/googleapis/doc-templates/pull/68 temporarily removed the relevant part of the template.
